maintainer "Stephen Crawley"
maintainer_email "s.crawley at uq dot edu dot au"
license "BSD"
description "Some recipes for general NeCTAR virtual configuration"
version "1.1.3"

depends "timezone-ii", ">= 0.2.0"
depends "hostsfile"
depends "logwatch"
depends "postfix"
depends "clamav"
depends "locale"
depends "sudo"
depends "users"
depends "python"
depends "chef-solo-search"
