maintainer "Stephen Crawley"
maintainer_email "s.crawley at uq dot edu dot au"
license "BSD"
description "Some recipes for Qcloud configuration"
version "0.0.1"

depends "timezone-ii", ">= 0.2.0"
depends "hostsfile"
depends "logwatch"
depends "postfix"
depends "clamav"
